config/routes.rb
ArtApp::Application.routes.draw do

  root 'posts#landing'
  resources :users, :sessions, :reviews, :posts


  # get '/posts/:id/reviews/new', to: 'reviews#new'
  # how do I carry over the posts ID to the reviews?

  get '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  get'/signin' => 'sessions#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :reviews
  validates :user_id, presence: true

  def self.all_posts_by user
    where(user_id: user.id)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  validates :post_id, presence: true
  after_create :average_reviews

  def self.all_reviews_by user
    where(user_id: user.id)
    # where review user_id is equal to the user's ID
  end


private

  def average_reviews
    post = Post.find(self.post_id)
    a = post.reviews.map{|r| r.score}
    avg = a.inject{ |sum, el| sum + el }.to_f / a.size
    post.update_attributes(:weight_score => avg)

    user = User.find(post.user_id)
    a = user.posts.map{|r| r.weight_score}
    avg = 3.0;
    unless a.nil?
      a.compact!
      avg = a.inject{ |sum, el| sum + el }.to_f / a.size
    end  
    user.update_attributes(:av_score => avg)
  end


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  has_many :posts
  has_many :reviews

  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  def compute_av_score 
      a = posts.map{|r| r.weight_score}
      a.inject{ |sum, el| sum + el }.to_f / a.size
  end

  def self.update_all
    User.all.each do |u|
      u.update_attributes(:av_score => compute_av_score)
      u.update_attributes.save
    end
  end


    private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def landing
    @posts = Post.all
  end

  def new
    @post = Post.new
    @user_id = params[:id]
  end

  def create
    new_post=params.require(:post).permit( :title, :text, :score)
    @post = current_user.posts.create(new_post)
    redirect_to post_path(@post.id)
  end

  def show
    @post = Post.find(params[:id])
    @author= User.find(@post.user_id)

    @review = Review.new
    @reviews = Review.where("post_id = ?", params[:id])

    render :show 
  end


  def destroy
    post = Post.find(params[:id])
    post.delete
    redirect_to(posts_path)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :signed_in_user, only: [:create, :new, :edit, :update]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @reviewee_id = params[:id]
    @reviews = Review.all
  end
  
  def create
    new_review=params.require(:review).permit( :title, :text, :score, :post_id)
    @review = Review.create(new_review)
    @review.update_attributes(user_id: current_user.id)
    
    render :json => @review

  end
  
  def show
    @review = Review.find(params[:id])

    render :show
    
  end

  def destroy
    review = Review.find(params[:id])
    review.delete
    redirect_to(reviews_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new
  end

    def my_profile
    @user = User.find(params[:id])
  end

  def create
    user=User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to user
    else
      # Create an error message and re-render the signin form.
      flash.now[:error]='Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
      sign_out
      redirect_to users_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users=User.all
  end

  def show
    @user = User.find(params[:id])
    @posts_by_user = Post.all_posts_by @user
    @reviews_by_user = Review.all_reviews_by @user
  end

  def new
    @user = User.new()
  end

  def create
    new_user = params.require(:user).permit(:name, :email, :password, :password_confirmation, :about_me)
    @user=User.new(new_user)
    if @user.save
      flash[:success] = "Welcome to ArtHub!"
      sign_in @user
      redirect_to current_user
    else
      render'new'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    render :show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def avatar_url(user)
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

      def avatar_url_large(user)
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=200"
  end

end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # SessionHelper manages @current_user, that's the user currently
  # signed in.

  # signs in supplied user, called from SessionController
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    # current_user is avilable in controllers and views!
    # This is an is an assignment, which we must define - see below
    # note that next line is a call to setter 'def current_user=(user)' below
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  # Authorization: signed_in_user is called in a before_filter
  # callback in each controller, see books/ingredients/recipe controllers
  # Ensures access to create/edit functions on if signed in.
  def signed_in_user
    unless signed_in?
      # If not signed in, save current location in session object
      # to be able to redirect after successful sign in.
      session[:return_to] = request.url
      # prompt sign in page
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  # signs out user by deleting @current_user and session cookie
  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  # Getter and setter for @current_user
  def current_user=(user)
    @current_user = user
  end

  # if current_user doesn't exist, check session cookie for user session
  # If exists, get the user record that belongs to that session.
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
        <h1> ArtHub</h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to "New Post", new_post_path %></li>
      <li><%= link_to "Sign in", signin_path, method: "get"%></li>
      <li><%= link_to "Sign up", signup_path, method: "get"%></li>
      <li><%= link_to "Sign out", signout_path, method: "delete"%></li>
      <li><%= link_to "View Users", users_path, method: "get"%></li>
      <li><%= link_to "View Recent Posts", root_path, method: "get"%></li>

      </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render :partial => 'layouts/header' %>
<head>



  <meta name="viewport" content="width=device-width, initial-scale=1.0" />


  <title>ArtApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script>$(document).foundation();</script>

<link href='http://fonts.googleapis.com/css?family=Nothing+You+Could+Do' rel='stylesheet' type='text/css'>

</body>
</html>

app/views/posts/landing.html.erb
<div class="index">

<h3>Recent Posts</h3>

<% @posts.each do |post| %>
  <div class="row">
     <div>
      <dl>
      <dd><a href="<%=post_path(post)%>"><%=post.title%></a></dd>
      <dd><%=post.text%></dd>
     </dl>
    </div>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="index">

<h3>Create a New Post</h3>

<div class="row">
  <div class="large-12 columns">
    <%= form_for(@post) do |f| %>
      <% unless @post.errors.count == 0   %>
        <div class="alert alert-error">
          The form contains <%= pluralize(@post.errors.count, "error") %>.
        </div>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
        </ul>
      <% end %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :text %>
      <%= f.text_area :text, :cols => "30", :rows => "25" %>
 
      <%= f.hidden_field :weight_score, :value=> [] %>    

      <%= f.submit "Create", class: "button" %>
    <% end %>
  </div>
</div>

</div>

app/views/posts/show.html.erb
  <div class="post">
  <h3><%= @post.title %>, Score: <%= @post.weight_score %></h3><br>

  <h3><%= image_tag avatar_url(@author) %>  By <%=@author.name%></h3>

     <div class="col-md-3">
      <p class="text-info"><%= @post.text %></p><br>
</div>

<%= render :partial => 'reviews/new', locals: {reviews: @reviews} %>

app/views/reviews/_index.html.erb
<div class="index">

<h3>Reviews of this Post</h3>

<div id="review_list">

<% @reviews.each do |review| %>
  <div class="row">
    <div class="span3 offset1">
      <dl>
      <dt><%=review.title%> (<%=review.score%>)</dt>
      <dd><%=review.text%></dd>
      </dl>
    </div>
  </div>
<% end %>

</div>

</div>

app/views/reviews/_new.html.erb
<div class="index">

  <h3>Review this Post</h3>

<div class="row">
  <div class="large-12 columns">
    <%= form_for(@review, remote: true) do |f| %>
      <% unless @review.errors.count == 0   %>
        <div class="alert alert-error">
          The form contains <%= pluralize(@review.errors.count, "error") %>.
        </div>
        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
        </ul>
      <% end %>

      <div class="small-5">

        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>

      <%= f.label :text %>
      <%= f.text_area :text, :cols => "30", :rows => "25" %>

      <div class="large-6 columns">
        <label>Score This Post</label>
        <input type="radio" name="review[score]" value="1" id="1"><label for="1">1</label>
        <input type="radio" name="review[score]" value="2" id="2"><label for="2">2</label>
        <input type="radio" name="review[score]" value="3" id="3"><label for="3">3</label>
        <input type="radio" name="review[score]" value="4" id="4"><label for="4">4</label>
        <input type="radio" name="review[score]" value="5" id="5"><label for="5">5</label>

      </div>

      <%= f.hidden_field :post_id, :value=> @post.id %>   

      <%= f.submit "Review", class: "button" %>
    <% end %>
  </div>
</div>

<%= render :partial => 'reviews/index', locals: {reviews: @reviews} %>


</div>

app/views/reviews/_show.html.erb
	<div class="review">
	<h3><%= @review.title %></h3><br>

     <div class="col-md-3">
      <p class="text-info"><%= @review.review_text %></p><br>
      <p class="text-info">Score: <%= @review.score %></p><br>
</div>

<ul class="nav nav-pills">
  <li><%= link_to('Delete Review', @review, :method => :delete, :confirm => 'Are you sure?') %></li>
  <li><%= link_to 'Return to Users', users_path %></li>
</ul>
</div>

app/views/reviews/index.html.erb
<%= render :partial => 'layouts/header' %>

<div class="index">

<h3>Reviews of this Post</h3>

<% @reviews.each do |review| %>
  <div class="row">
     <div class="span3 offset1">
     	<ul>
     	<li><a href="<%=review_path(review)%>"><%=review.title%></a></li>

     </ul>

</div>
  </div>
<% end %>
</div>

app/views/reviews/new.html.erb
<div class="index">


  <!-- add my real review form -->

  <h3>Review this Post</h3>

<div class="row">
  <div class="span15 offset3">
    <%= form_for(@review, remote: true) do |f| %>
      <% unless @review.errors.count == 0   %>
        <div class="alert alert-error">
          The form contains <%= pluralize(@review.errors.count, "error") %>.
        </div>
        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
        </ul>
      <% end %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :text %>
      <%= f.text_field :text %><br>

      <%= f.label :score %>
      <%= f.text_field :score %><br>

<!-- have to add a hidden value for the post id -->

      <%= f.submit "Review", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<%= render :partial => 'reviews/index', locals: {reviews: @reviews} %>


</div>

app/views/reviews/show.html.erb
	<div class="review">
	<h3><%= @review.title %></h3><br>

     <div class="col-md-3">
      <p class="text-info"><%= @review.review_text %></p><br>
      <p class="text-info">Score: <%= @review.score %></p><br>
</div>

<ul class="nav nav-pills">
  <li><%= link_to('Delete Review', @review, :method => :delete, :confirm => 'Are you sure?') %></li>
  <li><%= link_to 'Return to Users', users_path %></li>
</ul>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="index">

<h3> List of users</h3>


<% @users.each do |user| %>
  <div class="row">
     <div class="span3 offset1">
     	<a href="<%=user_path(user.id)%>"><%=user.name%></a>
      <p class="text-warning"><%= user.email %></p>

    </div>
  </div>
<% end %>

</div>

app/views/users/new.html.erb
<div class="index">

<h3>Welcome to the ArtHub Community!</h3>
<p>ArtHub is a new community of writers who want to see how they stack up. Join today, post your work, and get reviewed and scored by other writers like you.</p>

<h3>Sign up</h3>

  <div class="row">
    <div class="small-5">
      <%= form_for(@user) do |f| %>
        <% unless @user.errors.count == 0   %>
          <div class="alert alert-error">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
          </div>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
          <% end %>
          </ul>
        <% end %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %><br>

        <%= f.label :about_me %>
        <%= f.text_area :about_me, :cols => "30", :rows => "5" %>


        <!-- bootstrap for other fields in bio-->

        <%= f.submit "Create my account", class: "button" %>
      <% end %>
    </div>
  </div> 
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <div class="show_header">
      <h3><%= @user.name %>'s Page</h3>
      <h3>ArtHub Score: <%= @user.av_score %></h3> <br>
    </div>

    <div class="show">


<div class = "gravatar"><%= image_tag avatar_url_large(@user) %></div>

      <h3>Email:</h3>
      <p><%= @user.email %></p><br>

      <h3>About <%=@user.name%>:</h3>
      <p><%= @user.about_me %></p><br>


  <h3>Work by this user </h3>
    <% @posts_by_user.each do |post| %>
      <div class="row">
        <div class="span3 offset1">
          <ul>
            <li><a href="<%=post_path(post)%>"><%=post.title%></a></li>
            <ul>
              <li><%=post.text%></li>
            </ul>
          </ul>
        </div>
      </div>
    <% end %>
        </section>
      </aside>
      </div>

  <h3>Reviews by this User</h3>
    <% @reviews_by_user.each do |review| %>
      <div class="row">
        <div class="span3 offset1">
          <ul>
            <li><a href="<%=post_path(review.post_id)%>"><%=review.title%></a></li>
          </ul>
        </div>
      </div>
    <% end %>
        </section>
      </aside>
      </div>

</div>